### ISSUE TITLE
Codebraid breaks on pandoc citations.

### ISSUE THREAD

**Issue by Synthetica9** [gpoore/codebraid#12]
Minimal example:

```md
[@test]
```

Fails with:

```
$ codebraid pandoc /tmp/test.md 
Traceback (most recent call last):
  File "/nix/store/n1nd5j5m583llfbbmqm379kmg98335zg-codebraid-0.4.0/bin/.codebraid-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/n1nd5j5m583llfbbmqm379kmg98335zg-codebraid-0.4.0/lib/python3.7/site-packages/codebraid/cmdline.py", line 62, in main
    args.func(args)
  File "/nix/store/n1nd5j5m583llfbbmqm379kmg98335zg-codebraid-0.4.0/lib/python3.7/site-packages/codebraid/cmdline.py", line 85, in pandoc
    converter.code_braid()
  File "/nix/store/n1nd5j5m583llfbbmqm379kmg98335zg-codebraid-0.4.0/lib/python3.7/site-packages/codebraid/converters/base.py", line 1161, in code_braid
    self._extract_code_chunks()
  File "/nix/store/n1nd5j5m583llfbbmqm379kmg98335zg-codebraid-0.4.0/lib/python3.7/site-packages/codebraid/converters/pandoc.py", line 1146, in _extract_code_chunks
    self._load_and_process_initial_ast(source_string=source_string, single_source_name=source_name)
  File "/nix/store/n1nd5j5m583llfbbmqm379kmg98335zg-codebraid-0.4.0/lib/python3.7/site-packages/codebraid/converters/pandoc.py", line 1007, in _load_and_process_initial_ast
    node_type = node['t']
KeyError: 't'
```

**Comment by Synthetica9** [comment]
I did some experimentation, using `.get('t')` in a few places seems to fix everything.

So: 

```diff
diff --git a/codebraid/converters/pandoc.py b/codebraid/converters/pandoc.py
index 132a5f2..e03537c 100644
--- a/codebraid/converters/pandoc.py
+++ b/codebraid/converters/pandoc.py
@@ -510,7 +510,7 @@ def _get_walk_less_note_contents_closure(enumerate=enumerate, isinstance=isinsta
                 yield from walk_node_list_less_note_contents(obj)
             elif isinstance(obj, dict):
                 yield (obj, node_list, index)
-                if obj['t'] == 'Note':
+                if obj.get('t') == 'Note':
                     continue
                 obj_contents = obj.get('c', None)
                 if isinstance(obj_contents, list):
@@ -1004,7 +1004,7 @@ class PandocConverter(Converter):
                                            'SoftBreak', 'Span'])
         for node_tuple in self._walk_ast_less_note_contents(ast):
             node, parent_node_list, parent_node_list_index = node_tuple
-            node_type = node['t']
+            node_type = node.get('t')
             if node_type in ignorable_inline_node_types:
                 pass
             elif node_type == 'Str':
@@ -1212,7 +1212,7 @@ class PandocConverter(Converter):
             thaw_raw_node = self._thaw_raw_node
             for node_tuple in self._walk_ast(final_ast):
                 node, parent_node_list, parent_node_list_index = node_tuple
-                node_type = node['t']
+                node_type = node.get('t')
                 if node_type in ('Code', 'CodeBlock') and 'codebraid--temp' in node['c'][0][1]:
                     thaw_raw_node(node)
         else:
```

However, this is a blind replace on my part, simply replacing wherever it complained that it was broken, so I have no idea if this breaks anything else. Should I open a PR?

**Comment by gpoore** [comment]
It should be fixed in the last commit. Citations like that are represented in Pandoc's AST in a form that I hadn't previously encountered.

**Comment by Synthetica9** [comment]
Seems to fix it! Thank you for the quick turnaround :)
