### ISSUE TITLE
AttributeError and TypeError in normal use

### ISSUE THREAD

**Issue by WhosCounting** [gpoore/codebraid#3]
Hi,
This looks like a really nice project, and I really wanted to give it a try but unfortunately it crashes badly. First, invoking simply `codebraid` (without any args) results in:

```
Traceback (most recent call last):
  File "/home/<user>/venv/pyactr/bin/codebraid", line 11, in <module>
    sys.exit(main())
  File "/home/<user>/venv/pyactr/lib/python3.6/site-packages/codebraid/cmdline.py", line 57, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'

```

And using `codebraid pandoc rep.md -o rep.pdf`returns:

```
Traceback (most recent call last):
  File "/home/<user>/venv/pyactr/bin/codebraid", line 11, in <module>
    sys.exit(main())
  File "/home/<user>/venv/pyactr/lib/python3.6/site-packages/codebraid/cmdline.py", line 57, in main
    args.func(args)
  File "/home/<user>/venv/pyactr/lib/python3.6/site-packages/codebraid/cmdline.py", line 78, in pandoc
    other_pandoc_args=other_pandoc_args)
  File "/home/<user>/venv/pyactr/lib/python3.6/site-packages/codebraid/converters/pandoc.py", line 1143, in convert
    raise TypeError
TypeError
```

Do you know what could be wrong?

**Comment by gpoore** [comment]
It should work after the latest commit. I hadn't added compatibility for the case in which Pandoc determines the output format based on the output file name, rather than receiving the format explicitly via the `--to` flag (which wouldn't actually work in this case anyway, since Pandoc treats PDF as a special case and automatically uses an intermediary format).

**Comment by WhosCounting** [comment]
Thanks for your quick reply! Looks like everything works now :)
Keep up the good work
